// @ts-nocheck
'use client';

// Glass tokens live in tokens.css as CSS custom properties.
// They are not in the Tailwind theme (the preset comment says so explicitly),
// so we consume them via style={{ }} with var() references.
//
// NOTE: this page previously referenced --glass-surface-light, --glass-surface-medium,
// --glass-border, --glass-shadow, and --glass-backdrop-blur. None of those are ever
// generated by packages/tokens/src/generators/css.ts — they don't exist in tokens.css,
// so every property below was resolving to nothing and the panels rendered invisibly.
// (apps/web/src/app/global.css has the exact same bug — same undefined names.)
// Remapped to the tokens that actually exist: --color-surface-glass-*, --color-border-
// glass-border*, and --shadow-glass-shadow*. There's no dedicated "glass blur" token,
// so --blur-lg is used for backdrop-filter.
//
// To show glass properly the demo background must be visible behind the panel.
// We render each swatch over a green-to-gold gradient backdrop.

const glassSurfaces = [
  {
    name: 'surface-glass-subtle',
    cssVar: '--color-surface-glass-subtle',
    value: 'rgba(255,255,255,0.35)',
    label: 'Light',
  },
  {
    name: 'surface-glass-medium',
    cssVar: '--color-surface-glass-medium',
    value: 'rgba(255,255,255,0.55)',
    label: 'Medium',
  },
];

const allTokens = [
  { name: 'color-surface-glass-subtle', value: 'rgba(255,255,255,0.35)' },
  { name: 'color-surface-glass-medium', value: 'rgba(255,255,255,0.55)' },
  { name: 'blur-lg (used as glass backdrop blur)', value: '16px' },
  { name: 'color-border-glass-border', value: 'rgba(28,26,22,0.08)' },
  { name: 'shadow-glass-shadow', value: '0 4px 24px rgba(0,0,0,0.25), inset 0 1px 0 rgba(218,241,222,0.06)' },
];

export default function GlassPage() {
  return (
    <div>
      <h2 className="font-display text-h2 mb-space-4">Glass Tokens</h2>
      <p className="font-body text-body text-text-muted mb-space-4">
        Translucent surface tokens for the "forest mist" aesthetic. These are CSS custom properties in <code className="font-mono text-code bg-surface-default px-space-2 py-space-1 rounded-sm">tokens.css</code> — use them with <code className="font-mono text-code bg-surface-default px-space-2 py-space-1 rounded-sm">style={'{{ backgroundColor: "var(--color-surface-glass-subtle)" }}'}</code>, or add a utility class in <code className="font-mono text-code bg-surface-default px-space-2 py-space-1 rounded-sm">global.css</code>.
      </p>

      {/* Live demo – glass panels over a textured backdrop */}
      <div className="mb-space-16">
        <h3 className="font-display text-h3 mb-space-6 pb-space-2 border-b border-border-light">Surfaces</h3>
        <div className="flex flex-wrap gap-space-8">
          {glassSurfaces.map((s) => (
            <div key={s.name} className="flex flex-col gap-space-3">
              {/* Backdrop */}
              <div
                className="relative w-size-64 h-size-40 rounded-md overflow-hidden"
                style={{
                  background: 'linear-gradient(135deg, var(--color-green-base) 0%, var(--color-gold-base) 100%)',
                }}
              >
                {/* Decorative circles so transparency reads clearly */}
                <div
                  className="absolute rounded-full"
                  style={{
                    width: 80,
                    height: 80,
                    top: -20,
                    right: -20,
                    backgroundColor: 'var(--color-gold-light)',
                    opacity: 0.6,
                  }}
                />
                <div
                  className="absolute rounded-full"
                  style={{
                    width: 60,
                    height: 60,
                    bottom: -10,
                    left: 20,
                    backgroundColor: 'var(--color-surface-base)',
                    opacity: 0.4,
                  }}
                />
                {/* Glass panel */}
                <div
                  className="absolute inset-space-4 rounded-md flex flex-col items-center justify-center"
                  style={{
                    inset: 'var(--space-4)',
                    backgroundColor: `var(${s.cssVar})`,
                    backdropFilter: 'blur(var(--blur-lg))',
                    WebkitBackdropFilter: 'blur(var(--blur-lg))',
                    border: '1px solid var(--color-border-glass-border)',
                    boxShadow: 'var(--shadow-glass-shadow)',
                  }}
                >
                  <span className="font-body text-label tracking-label text-text-inverse">{s.label}</span>
                  <span className="font-mono text-caption text-text-inverse" style={{ opacity: 0.8 }}>
                    {s.value}
                  </span>
                </div>
              </div>
              <span className="font-mono text-caption text-text-muted">--{s.name}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Token reference table */}
      <div>
        <h3 className="font-display text-h3 mb-space-6 pb-space-2 border-b border-border-light">Token Reference</h3>
        <div className="flex flex-col gap-space-3">
          {allTokens.map(({ name, value }) => (
            <div key={name} className="flex items-start gap-space-4 p-space-4 bg-surface-elevated border border-border-light rounded-md">
              <span className="w-size-68 shrink-0 font-mono text-label text-text-primary">--{name}</span>
              <span className="font-mono text-caption text-text-muted break-all">{value}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
